# Usar a imagem oficial do Ubuntu
FROM rtmedical/mc:geant-10.7.1

# Definir variáveis de ambiente necessárias
ENV DEBIAN_FRONTEND=noninteractive
ENV GEANT4_VERSION=v10.7.1
ENV ITK_VERSION=v4.13.3
ENV TORCH_VERSION=1.7.0
ARG GATE_VERSION=v9.1
ENV ROOT_DIR=/root/software/root
ENV GEANT4_DIR=/root/software/geant4
ENV ITK_DIR=/root/software/itk
ENV TORCH_DIR=/root/software/libtorch


# Desabilitar verificação SSL do git (se necessário)
RUN git config --global http.sslVerify false



# Instalar o ITK com RTK
RUN mkdir -p $ITK_DIR/src $ITK_DIR/build && \
    cd $ITK_DIR/src && \
    git clone --branch $ITK_VERSION https://github.com/InsightSoftwareConsortium/ITK.git --depth 1 . && \
    cd $ITK_DIR/build && \
    cmake -DCMAKE_CXX_STANDARD=17 \
          -DCMAKE_INSTALL_PREFIX=$ITK_DIR/install \
          -DBUILD_TESTING=OFF \
          -DITK_USE_FFTWD=ON \
          -DITK_USE_FFTWF=ON \
          -DITK_USE_SYSTEM_FFTW=ON \
          -DITK_MINIMUM_COMPLIANCE_LEVEL=3 \
          -DModule_RTK=ON \
          -DREMOTE_GIT_TAG_RTK=master \
          $ITK_DIR/src && \
    make -j$(nproc) install && \
    find $ITK_DIR/install -name ITKConfig.cmake && \
    rm -rf $ITK_DIR/src

# Instalar o Torch com certificados atualizados
RUN apt-get update && apt-get install -y ca-certificates && \
    mkdir -p $TORCH_DIR && \
    cd /root/software && \
    wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-$TORCH_VERSION%2Bcpu.zip && \
    unzip libtorch-cxx11-abi-shared-with-deps-$TORCH_VERSION+cpu.zip -d $TORCH_DIR && \
    rm libtorch-cxx11-abi-shared-with-deps-$TORCH_VERSION+cpu.zip

# Atualizar CMAKE_PREFIX_PATH para incluir o diretório de instalação do Geant4, ITK e CLHEP
ENV CMAKE_PREFIX_PATH=$GEANT4_DIR/install:$ITK_DIR/install:/root/software/clhep/install:$CMAKE_PREFIX_PATH
ENV LD_LIBRARY_PATH=$ITK_DIR/install/lib:/root/software/clhep/install/lib:$LD_LIBRARY_PATH

# Clonar o repositório do Gate
RUN git clone https://github.com/OpenGATE/Gate.git /root/software/gate/src && \
    cd /root/software/gate/src && \
    git checkout ${GATE_VERSION}

# Modificar o arquivo para comentar a linha fclose
RUN sed -i '735s/^/\/\//' /root/software/gate/src/source/digits_hits/src/GatePhaseSpaceActor.cc

# Construir o Gate
WORKDIR /root/build
RUN cmake -DGATE_USE_TORCH=ON \
          -DTorch_DIR=$TORCH_DIR/libtorch/share/cmake/Torch \
          -DGATE_USE_RTK=ON \
          -DITK_DIR=$ITK_DIR/install/lib/cmake/ITK-4.13 \
          -DGATE_COMPILE_GATEDIGIT=ON \
          -DGATE_USE_OPTICAL=ON \
          -DCLHEP_ROOT_DIR=/root/software/clhep/install \
          -DBUILD_TESTING=ON \
          /root/software/gate/src && \
    make -j$(nproc)

# Definir o comando padrão
CMD ["bash"]
