# Usar a imagem oficial do Ubuntu 20.04
FROM ubuntu:20.04

# Definir variáveis de ambiente necessárias
ENV DEBIAN_FRONTEND=noninteractive
ENV ROOT_VERSION=v6-19-02
ENV CLHEP_VERSION=2.4.4.0
ENV GEANT4_VERSION=v10.7.1
ENV ITK_VERSION=v4.13.3
ENV TORCH_VERSION=1.7.0
ARG GATE_VERSION=v9.1

ENV ROOT_DIR=/root/software/root
ENV GEANT4_DIR=/root/software/geant4
ENV ITK_DIR=/root/software/itk
ENV TORCH_DIR=/root/software/libtorch
ENV CLHEP_DIR=/root/software/clhep

# Atualizar pacotes e instalar dependências gerais
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    make \
    binutils \
    libx11-dev \
    libtbb-dev \
    libxpm-dev \
    libxft-dev \
    libxext-dev \
    qtbase5-dev \
    qt5-qmake \
    git \
    cmake \
    libssl-dev \
    python3.8-dev \
    python3-pip \
    ccache \
    fftw3-dev \
    wget \
    unzip \
    curl \
    libxml2-dev \
    nano \
    mesa-utils \
    libglu1-mesa-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Instalar pacotes Python e dependências adicionais
RUN pip3 install uproot==3.12.0 click==7.1.2 SimpleITK==2.0.1 numpy pandas matplotlib scipy pydicom stl numpy-stl scikit-learn

# Criar diretórios para instalação
WORKDIR /root
RUN mkdir -p $ROOT_DIR $CLHEP_DIR $GEANT4_DIR $ITK_DIR $TORCH_DIR /root/software/option_dependencies


# Definir o comando padrão (opcional)
CMD ["/bin/bash"]