# Usar a imagem oficial do Ubuntu 20.04
FROM  rtmedical/mc:ubuntu

# Definir variáveis de ambiente necessárias
ENV DEBIAN_FRONTEND=noninteractive
ENV ROOT_VERSION=v6-19-02
ENV CLHEP_VERSION=CLHEP_2_4_4_0
ENV GEANT4_VERSION=v10.7.1
ENV ITK_VERSION=v4.13.3
ENV TORCH_VERSION=1.7.0
ARG GATE_VERSION=v9.1

ENV ROOT_DIR=/root/software/root
ENV GEANT4_DIR=/root/software/geant4
ENV ITK_DIR=/root/software/itk
ENV TORCH_DIR=/root/software/libtorch
ENV CLHEP_DIR=/root/software/clhep

RUN apt-get update && apt-get install -y \
    qt5-default \
    libqt5opengl5-dev \
    libglu1-mesa-dev \
    libgl1-mesa-dev \
    libx11-dev

# Instalar o CLHEP
RUN git clone --branch $CLHEP_VERSION https://gitlab.cern.ch/CLHEP/CLHEP.git --depth 1 $CLHEP_DIR/src && \
    mkdir -p $CLHEP_DIR/build && \
    cd $CLHEP_DIR/build && \
    cmake $CLHEP_DIR/src \
          -DCMAKE_CXX_STANDARD=17 \
          -DCMAKE_INSTALL_PREFIX=$CLHEP_DIR/install && \
    make -j$(nproc) install && \
    rm -rf $CLHEP_DIR/src $CLHEP_DIR/build

    

# Instalar o ROOT
RUN git clone --branch $ROOT_VERSION https://github.com/root-project/root.git --depth 1 $ROOT_DIR/src && \
    mkdir -p $ROOT_DIR/build && \
    cd $ROOT_DIR/build && \
    cmake $ROOT_DIR/src \
          -DCMAKE_CXX_STANDARD=17 \
          -Dpython=OFF \
          -Dpyroot=OFF \
          -Dclad=OFF \
          -Dxrootd=OFF \
          -DCMAKE_INSTALL_PREFIX=$ROOT_DIR/install && \
    make -j$(nproc) install && \
    rm -rf $ROOT_DIR/src $ROOT_DIR/build

# Instalar o Geant4
RUN git clone --branch $GEANT4_VERSION https://github.com/Geant4/geant4.git --depth 1 $GEANT4_DIR/src && \
    mkdir -p $GEANT4_DIR/build $GEANT4_DIR/data && \
    cd $GEANT4_DIR/build && \
    cmake -DGEANT4_INSTALL_DATA=ON \
          -DGEANT4_BUILD_MULTITHREADED=OFF \
          -DGEANT4_INSTALL_DATADIR=$GEANT4_DIR/data \
          -DCMAKE_INSTALL_PREFIX=$GEANT4_DIR/install \
          -DGEANT4_USE_QT=ON \
          -DGEANT4_USE_OPENGL_X11=ON \
          -DGEANT4_USE_SYSTEM_CLHEP=ON \
          -DCLHEP_ROOT_DIR=$CLHEP_DIR/install \
          $GEANT4_DIR/src && \
    make -j$(nproc) install && \
    rm -rf $GEANT4_DIR/src $GEANT4_DIR/build

# Configurações finais
RUN echo "export PATH=$ROOT_DIR/install/bin:$GEANT4_DIR/install/bin:$CLHEP_DIR/install/bin:\$PATH" >> /root/.bashrc

# Definir o comando padrão (opcional)
CMD ["/bin/bash"]
