# Usar a imagem oficial do Ubuntu 20.04
FROM rtmedical/mc:ubuntuubuntu:20.04

# Instalar o CLHEP
# Build CLHEP
RUN mkdir -p $CLHEP_DIR/src $CLHEP_DIR/bin $CLHEP_DIR/install && \
    cd $CLHEP_DIR && \
    wget -q $CLHEP_URL && \
    tar -zxf $CLHEP_File -C ./src --strip-components=2 && \
    cd bin && \
    cmake -DCMAKE_CXX_FLAGS=-std=c++17 -DCMAKE_INSTALL_PREFIX=$CLHEP_DIR/install ../src && \
    cmake --build . -- -j && \
    cmake --build . --target install && \
    cd .. && \
    rm -rf bin src
    

# Instalar o ROOT
RUN git clone --branch $ROOT_VERSION https://github.com/root-project/root.git --depth 1 $ROOT_DIR/src && \
    mkdir -p $ROOT_DIR/build && \
    cd $ROOT_DIR/build && \
    cmake $ROOT_DIR/src \
          -DCMAKE_CXX_STANDARD=17 \
          -Dpython=OFF \
          -Dpyroot=OFF \
          -Dclad=OFF \
          -Dxrootd=OFF \
          -DCMAKE_INSTALL_PREFIX=$ROOT_DIR/install && \
    make -j$(nproc) install && \
    rm -rf $ROOT_DIR/src $ROOT_DIR/build

# Instalar o Geant4
RUN git clone --branch $GEANT4_VERSION https://github.com/Geant4/geant4.git --depth 1 $GEANT4_DIR/src && \
    mkdir -p $GEANT4_DIR/build $GEANT4_DIR/data && \
    cd $GEANT4_DIR/build && \
    cmake -DGEANT4_INSTALL_DATA=ON \
          -DGEANT4_BUILD_MULTITHREADED=OFF \
          -DGEANT4_INSTALL_DATADIR=$GEANT4_DIR/data \
          -DCMAKE_INSTALL_PREFIX=$GEANT4_DIR/install \
          -DGEANT4_USE_QT=ON \
          -DGEANT4_USE_OPENGL_X11=ON \
          -DGEANT4_USE_SYSTEM_CLHEP=ON \
          -DCLHEP_ROOT_DIR=$CLHEP_DIR/install \
          $GEANT4_DIR/src && \
    make -j$(nproc) install && \
    rm -rf $GEANT4_DIR/src $GEANT4_DIR/build

# Configurações finais
RUN echo "export PATH=$ROOT_DIR/install/bin:$GEANT4_DIR/install/bin:$CLHEP_DIR/install/bin:\$PATH" >> /root/.bashrc

# Definir o comando padrão (opcional)
CMD ["/bin/bash"]
